# Generated by Django 4.0.3 on 2022-04-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCustomers',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bhs_app.customer')),
            ],
            bases=('bhs_app.customer',),
        ),
    ]
